[2024-03-29T16:32:56.079+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: grobid_extraction.extract_text manual__2024-03-29T16:32:52.117703+00:00 [queued]>
[2024-03-29T16:32:56.102+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: grobid_extraction.extract_text manual__2024-03-29T16:32:52.117703+00:00 [queued]>
[2024-03-29T16:32:56.103+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T16:32:56.145+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_text> on 2024-03-29 16:32:52.117703+00:00
[2024-03-29T16:32:56.156+0000] {standard_task_runner.py:60} INFO - Started process 926 to run task
[2024-03-29T16:32:56.164+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'grobid_extraction', 'extract_text', 'manual__2024-03-29T16:32:52.117703+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/grobid_extraction.py', '--cfg-path', '/tmp/tmpctb6xh_h']
[2024-03-29T16:32:56.169+0000] {standard_task_runner.py:88} INFO - Job 186: Subtask extract_text
[2024-03-29T16:32:56.315+0000] {task_command.py:423} INFO - Running <TaskInstance: grobid_extraction.extract_text manual__2024-03-29T16:32:52.117703+00:00 [running]> on host 9bbf17010fdd
[2024-03-29T16:32:56.575+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shubhpatel2800@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='grobid_extraction' AIRFLOW_CTX_TASK_ID='extract_text' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T16:32:52.117703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T16:32:52.117703+00:00'
[2024-03-29T16:32:58.124+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/grobid_extraction.py", line 51, in extract_text_from_pdf
    s3.download_file('assignment-4bigdata', '2024-l1-topics-combined-2.pdf', '/tmp/processed_data/l1.pdf')
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/s3/inject.py", line 171, in download_file
    return transfer.download_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/download.py", line 642, in _main
    fileobj.seek(offset)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/utils.py", line 378, in seek
    self._open_if_needed()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/utils.py", line 361, in _open_if_needed
    self._fileobj = self._open_function(self._filename, self._mode)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/utils.py", line 272, in open
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/processed_data/l1.pdf.a1C40c23'
[2024-03-29T16:32:58.156+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=grobid_extraction, task_id=extract_text, execution_date=20240329T163252, start_date=20240329T163256, end_date=20240329T163258
[2024-03-29T16:32:58.189+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 186 for task extract_text ([Errno 2] No such file or directory: '/tmp/processed_data/l1.pdf.a1C40c23'; 926)
[2024-03-29T16:32:58.232+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-29T16:32:58.276+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
