[2024-03-29T16:15:44.583+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: grobid_extraction.extract_text manual__2024-03-29T16:15:38.052580+00:00 [queued]>
[2024-03-29T16:15:44.603+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: grobid_extraction.extract_text manual__2024-03-29T16:15:38.052580+00:00 [queued]>
[2024-03-29T16:15:44.604+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T16:15:44.627+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_text> on 2024-03-29 16:15:38.052580+00:00
[2024-03-29T16:15:44.638+0000] {standard_task_runner.py:60} INFO - Started process 639 to run task
[2024-03-29T16:15:44.646+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'grobid_extraction', 'extract_text', 'manual__2024-03-29T16:15:38.052580+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/grobid_extraction.py', '--cfg-path', '/tmp/tmpvnzjgwle']
[2024-03-29T16:15:44.651+0000] {standard_task_runner.py:88} INFO - Job 180: Subtask extract_text
[2024-03-29T16:15:44.733+0000] {task_command.py:423} INFO - Running <TaskInstance: grobid_extraction.extract_text manual__2024-03-29T16:15:38.052580+00:00 [running]> on host 9bbf17010fdd
[2024-03-29T16:15:44.873+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shubhpatel2800@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='grobid_extraction' AIRFLOW_CTX_TASK_ID='extract_text' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T16:15:38.052580+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T16:15:38.052580+00:00'
[2024-03-29T16:15:46.067+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/grobid_extraction.py", line 69, in extract_text_from_pdf
    structured_data = xml_to_structured_text(xml_data)
  File "/opt/airflow/dags/grobid_extraction.py", line 96, in xml_to_structured_text
    xml_str = xml_data.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
[2024-03-29T16:15:46.095+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=grobid_extraction, task_id=extract_text, execution_date=20240329T161538, start_date=20240329T161544, end_date=20240329T161546
[2024-03-29T16:15:46.130+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 180 for task extract_text ('NoneType' object has no attribute 'decode'; 639)
[2024-03-29T16:15:46.146+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-29T16:15:46.190+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
